<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CarritodePedidos.aspx.cs" Inherits="Vistas.CarritodePedidos" %>
<%@ Register Src="~/Cliente/VistaMenuCliente.ascx" TagName="Menu" TagPrefix="uc" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="../Estilos/estilos.css">
   <%-- <link rel="stylesheet" type="text/css" href="../Estilos/StyleMenu.css"/>--%>
    <style type="text/css">
        .auto-style1 {
            width: 845px;
        }
        .auto-style2 {
            width: 864px;
            height: 683px;
        }
        .header-container {
            text-align: center;
        }
    </style>
</head>

<body class="bodyBlanco">
    <uc:menu runat="server" />
    <form id="form1" runat="server" class="auto-style2">
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <asp:Label ID="lblNombreUsuario" runat="server" CssClass="nombre-usuario"></asp:Label>
        
            
       
        <div>
            <br />
            <asp:Label ID="lblTituloCarrito" runat="server" Text="SU PEDIDO CONTIENE" CssClass="labelPrincipal"></asp:Label>
            <br />
            <br />
            <br />
        </div>
        <br />
        <div>
            <asp:GridView ID="gv_Ordenes" runat="server" AutoGenerateColumns="False"  AutoGenerateDeleteButton="true" OnRowDeleting="gv_Ordenes_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" Height="434px" Width="583px" >
                <AlternatingRowStyle BackColor="White"  Wrap="False" />
                <Columns>
                    <asp:BoundField DataField="Nombre del Producto" HeaderText="Nombre del Producto" />
                    <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" />
                    <asp:BoundField DataField="Precio" HeaderText="Precio" />
                    <asp:BoundField DataField="Subtotal" HeaderText="Subtotal" />
                </Columns>
                <EditRowStyle BackColor="#6699ff" Wrap="False"/>
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>
        <br />
        <br />
        <asp:Button ID="btnConfirmarPedido" CssClass="BotonPrincipal" runat="server" Text="Confirmar Pedido" OnClick="btnConfirmarPedido_Click1" />
        <br />
        <div>
            <asp:Label ID="lblMensajeConfirmacion" runat="server" CssClass="labelPrincipal"></asp:Label>
        </div>
    </form>
</body>
</html>
